# Generated by Django 5.2.7 on 2025-10-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.item')),
            ],
        ),
    ]
